/**
 * Intima.ai - API
 * Bem vindo a documentação da API do [Intima.ai](https://app.intima.ai). Está documentação cobre todas as ações disponíveis dentro do Intima.ai e as disponibilizam como `ENDPOINTS` que podem ser integrados e utilizados por outros serviços ou aplicações, bastando somente possuir o `Token de acesso da API`.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IntimaaiApi) {
      root.IntimaaiApi = {};
    }
    root.IntimaaiApi.Documento = factory(root.IntimaaiApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Documento model module.
   * @module model/Documento
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Documento</code>.
   * @alias module:model/Documento
   * @class
   */
  var exports = function() {
    var _this = this;
  };

  /**
 * Constructs a new <code>Documento</code>.
 * @alias module:model/Documento
 * @class
 */
  var exports = function (data) {
    if (data) {
      var obj = obj || new exports();

      if (data.hasOwnProperty('arquivo')) {
        obj['arquivo'] = ApiClient.convertToType(data['arquivo'], 'Blob');
      }
      if (data.hasOwnProperty('tipo_documento')) {
        obj['tipo_documento'] = ApiClient.convertToType(data['tipo_documento'], 'Number');
      }
      if (data.hasOwnProperty('descricao_documento')) {
        obj['descricao_documento'] = ApiClient.convertToType(data['descricao_documento'], 'String');
      }
      if (data.hasOwnProperty('order')) {
        obj['order'] = ApiClient.convertToType(data['order'], 'Number');
      }
    }
    return obj;
  };

  /**
   * Constructs a <code>Documento</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Documento} obj Optional instance to populate.
   * @return {module:model/Documento} The populated <code>Documento</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('arquivo')) {
        obj['arquivo'] = ApiClient.convertToType(data['arquivo'], 'Blob');
      }
      if (data.hasOwnProperty('tipo_documento')) {
        obj['tipo_documento'] = ApiClient.convertToType(data['tipo_documento'], 'Number');
      }
      if (data.hasOwnProperty('descricao_documento')) {
        obj['descricao_documento'] = ApiClient.convertToType(data['descricao_documento'], 'String');
      }
      if (data.hasOwnProperty('order')) {
        obj['order'] = ApiClient.convertToType(data['order'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Blob} arquivo
   */
  exports.prototype['arquivo'] = undefined;
  /**
   * @member {Number} tipo_documento
   */
  exports.prototype['tipo_documento'] = undefined;
  /**
   * @member {String} descricao_documento
   */
  exports.prototype['descricao_documento'] = undefined;
  /**
   * @member {Number} order
   */
  exports.prototype['order'] = undefined;



  return exports;
}));


