/**
 * Intima.ai - API
 * Bem vindo a documentação da API do [Intima.ai](https://app.intima.ai). Está documentação cobre todas as ações disponíveis dentro do Intima.ai e as disponibilizam como `ENDPOINTS` que podem ser integrados e utilizados por outros serviços ou aplicações, bastando somente possuir o `Token de acesso da API`.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ActionsStatusResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ActionsStatusResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.IntimaaiApi) {
      root.IntimaaiApi = {};
    }
    root.IntimaaiApi.AcoesApi = factory(root.IntimaaiApi.ApiClient, root.IntimaaiApi.ActionsStatusResponse);
  }
}(this, function(ApiClient, ActionsStatusResponse) {
  'use strict';

  /**
   * Acoes service.
   * @module api/AcoesApi
   * @version 1.0.0
   */

  /**
   * Constructs a new AcoesApi. 
   * @alias module:api/AcoesApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the actionsStatusByPjeActionIdGet operation.
     * @callback module:api/AcoesApi~actionsStatusByPjeActionIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ActionsStatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getActionStatus
     * Checa o resultado de uma ação
     * @param {Number} pjeActionId é fornecido após se realizar a requisição de qualquer ação para o Intima.ai
     * @param {module:api/AcoesApi~actionsStatusByPjeActionIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ActionsStatusResponse}
     */
    this.actionsStatusByPjeActionIdGet = function(pjeActionId, callback) {
      var postBody = null;

      // verify the required parameter 'pjeActionId' is set
      if (pjeActionId === undefined || pjeActionId === null) {
        throw new Error("O parametro 'pjeActionId' é obrigatório!");
      }

      var pathParams = {
        'pje_action_id': pjeActionId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ActionsStatusResponse;

      return this.apiClient.callApi(
        '/actions/status/{pje_action_id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
