/**
 * Intima.ai - API
 * Bem vindo a documentação da API do [Intima.ai](https://app.intima.ai). Está documentação cobre todas as ações disponíveis dentro do Intima.ai e as disponibilizam como `ENDPOINTS` que podem ser integrados e utilizados por outros serviços ou aplicações, bastando somente possuir o `Token de acesso da API`.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ActionsProcessDocsResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ActionsProcessDocsResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.IntimaaiApi) {
      root.IntimaaiApi = {};
    }
    root.IntimaaiApi.EscutasApi = factory(root.IntimaaiApi.ApiClient, root.IntimaaiApi.ActionsProcessDocsResponse);
  }
}(this, function(ApiClient, ActionsProcessDocsResponse) {
  'use strict';

  /**
   * Escutas service.
   * @module api/EscutasApi
   * @version 1.0.0
   */

  /**
   * Constructs a new EscutasApi. 
   * @alias module:api/EscutasApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createProcessEscuta operation.
     * @callback module:api/EscutasApi~createProcessEscutaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ActionsProcessDocsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createProcessEscuta
     * Realiza uma nova escuta processual
     * @param {Number} pjeAuthId é o id referente ao tribunal cadastrado em \&quot;Tribunais ativos\&quot; no Intima.ai
     * @param {String} processo 
     * @param {module:api/EscutasApi~createProcessEscutaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ActionsProcessDocsResponse}
     */
    this.createProcessEscuta = function(pjeAuthId, processo, callback) {
      var postBody = null;

      // verify the required parameter 'pjeAuthId' is set
      if (pjeAuthId === undefined || pjeAuthId === null) {
        throw new Error("O parametro 'pjeAuthId' é obrigatório!");
      }

      // verify the required parameter 'processo' is set
      if (processo === undefined || processo === null) {
        throw new Error("O parametro 'processo' é obrigatório!");
      }

      var pathParams = {
        'pje_auth_id': pjeAuthId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'processo': processo
      };

      var authNames = ['api_token'];
      var contentTypes = ['application/x-www-form-urlencoded'];
      var accepts = ['application/json'];
      var returnType = ActionsProcessDocsResponse;

      return this.apiClient.callApi(
        '/actions/process-docs/{pje_auth_id}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
