/**
 * Intima.ai - API
 * Bem vindo a documentação da API do [Intima.ai](https://app.intima.ai). Está documentação cobre todas as ações disponíveis dentro do Intima.ai e as disponibilizam como `ENDPOINTS` que podem ser integrados e utilizados por outros serviços ou aplicações, bastando somente possuir o `Token de acesso da API`.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ActionsProcessProtocolResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ActionsProcessProtocolResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.IntimaaiApi) {
      root.IntimaaiApi = {};
    }
    root.IntimaaiApi.ProtocolosApi = factory(root.IntimaaiApi.ApiClient, root.IntimaaiApi.ActionsProcessProtocolResponse);
  }
}(this, function(ApiClient, ActionsProcessProtocolResponse) {
  'use strict';

  /**
   * Protocolos service.
   * @module api/ProtocolosApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ProtocolosApi. 
   * @alias module:api/ProtocolosApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the actionsProcessProtocolByPjeAuthIdPost operation.
     * @callback module:api/ProtocolosApi~actionsProcessProtocolByPjeAuthIdPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ActionsProcessProtocolResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createProcessProtocolo
     * Realiza um novo protocolo
     * @param {Number} pjeAuthId é o id referente ao tribunal cadastrado em \&quot;Tribunais ativos\&quot; no Intima.ai
     * @param {String} numeroProcesso 
     * @param {Number} tipoDocumentoMensagemGeral 
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} opts.documentos 
     * @param {module:api/ProtocolosApi~actionsProcessProtocolByPjeAuthIdPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ActionsProcessProtocolResponse}
     */
    this.actionsProcessProtocolByPjeAuthIdPost = function(pjeAuthId, numeroProcesso, tipoDocumentoMensagemGeral, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'pjeAuthId' is set
      if (pjeAuthId === undefined || pjeAuthId === null) {
        throw new Error("Missing the required parameter 'pjeAuthId' when calling actionsProcessProtocolByPjeAuthIdPost");
      }

      // verify the required parameter 'numeroProcesso' is set
      if (numeroProcesso === undefined || numeroProcesso === null) {
        throw new Error("Missing the required parameter 'numeroProcesso' when calling actionsProcessProtocolByPjeAuthIdPost");
      }

      // verify the required parameter 'tipoDocumentoMensagemGeral' is set
      if (tipoDocumentoMensagemGeral === undefined || tipoDocumentoMensagemGeral === null) {
        throw new Error("Missing the required parameter 'tipoDocumentoMensagemGeral' when calling actionsProcessProtocolByPjeAuthIdPost");
      }


      var pathParams = {
        'pje_auth_id': pjeAuthId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'numero_processo': numeroProcesso,
        'tipo_documento_mensagem_geral': tipoDocumentoMensagemGeral,
        'documentos': this.apiClient.buildCollectionParam(opts['documentos'], 'multi')
      };

      var authNames = ['api_token'];
      var contentTypes = ['application/x-www-form-urlencoded'];
      var accepts = ['application/json'];
      var returnType = ActionsProcessProtocolResponse;

      return this.apiClient.callApi(
        '/actions/process-protocol/{pje_auth_id}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
