/**
 * Intima.ai - API
 * Bem vindo a documentação da API do [Intima.ai](https://app.intima.ai). Está documentação cobre todas as ações disponíveis dentro do Intima.ai e as disponibilizam como `ENDPOINTS` que podem ser integrados e utilizados por outros serviços ou aplicações, bastando somente possuir o `Token de acesso da API`.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IntimaaiApi);
  }
}(this, function(expect, IntimaaiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IntimaaiApi.Documento();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Documento', function() {
    it('should create an instance of Documento', function() {
      // uncomment below and update the code to test Documento
      //var instance = new IntimaaiApi.Documento();
      //expect(instance).to.be.a(IntimaaiApi.Documento);
    });

    it('should have the property arquivo (base name: "arquivo")', function() {
      // uncomment below and update the code to test the property arquivo
      //var instance = new IntimaaiApi.Documento();
      //expect(instance).to.be();
    });

    it('should have the property tipoDocumento (base name: "tipo_documento")', function() {
      // uncomment below and update the code to test the property tipoDocumento
      //var instance = new IntimaaiApi.Documento();
      //expect(instance).to.be();
    });

    it('should have the property descricaoDocumento (base name: "descricao_documento")', function() {
      // uncomment below and update the code to test the property descricaoDocumento
      //var instance = new IntimaaiApi.Documento();
      //expect(instance).to.be();
    });

    it('should have the property order (base name: "order")', function() {
      // uncomment below and update the code to test the property order
      //var instance = new IntimaaiApi.Documento();
      //expect(instance).to.be();
    });

  });

}));
