/**
 * Intima.ai - API
 * Bem vindo a documentação da API do [Intima.ai](https://app.intima.ai). Está documentação cobre todas as ações disponíveis dentro do Intima.ai e as disponibilizam como `ENDPOINTS` que podem ser integrados e utilizados por outros serviços ou aplicações, bastando somente possuir o `Token de acesso da API`.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IntimaaiApi);
  }
}(this, function(expect, IntimaaiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IntimaaiApi.IntimacoesResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IntimacoesResponse', function() {
    it('should create an instance of IntimacoesResponse', function() {
      // uncomment below and update the code to test IntimacoesResponse
      //var instance = new IntimaaiApi.IntimacoesResponse();
      //expect(instance).to.be.a(IntimaaiApi.IntimacoesResponse);
    });

    it('should have the property currentPage (base name: "current_page")', function() {
      // uncomment below and update the code to test the property currentPage
      //var instance = new IntimaaiApi.IntimacoesResponse();
      //expect(instance).to.be();
    });

    it('should have the property data (base name: "data")', function() {
      // uncomment below and update the code to test the property data
      //var instance = new IntimaaiApi.IntimacoesResponse();
      //expect(instance).to.be();
    });

    it('should have the property firstPageUrl (base name: "first_page_url")', function() {
      // uncomment below and update the code to test the property firstPageUrl
      //var instance = new IntimaaiApi.IntimacoesResponse();
      //expect(instance).to.be();
    });

    it('should have the property from (base name: "from")', function() {
      // uncomment below and update the code to test the property from
      //var instance = new IntimaaiApi.IntimacoesResponse();
      //expect(instance).to.be();
    });

    it('should have the property lastPage (base name: "last_page")', function() {
      // uncomment below and update the code to test the property lastPage
      //var instance = new IntimaaiApi.IntimacoesResponse();
      //expect(instance).to.be();
    });

    it('should have the property lastPageUrl (base name: "last_page_url")', function() {
      // uncomment below and update the code to test the property lastPageUrl
      //var instance = new IntimaaiApi.IntimacoesResponse();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instance = new IntimaaiApi.IntimacoesResponse();
      //expect(instance).to.be();
    });

    it('should have the property perPage (base name: "per_page")', function() {
      // uncomment below and update the code to test the property perPage
      //var instance = new IntimaaiApi.IntimacoesResponse();
      //expect(instance).to.be();
    });

    it('should have the property to (base name: "to")', function() {
      // uncomment below and update the code to test the property to
      //var instance = new IntimaaiApi.IntimacoesResponse();
      //expect(instance).to.be();
    });

    it('should have the property total (base name: "total")', function() {
      // uncomment below and update the code to test the property total
      //var instance = new IntimaaiApi.IntimacoesResponse();
      //expect(instance).to.be();
    });

  });

}));
