/**
 * Intima.ai - API
 * Bem vindo a documentação da API do [Intima.ai](https://app.intima.ai). Está documentação cobre todas as ações disponíveis dentro do Intima.ai e as disponibilizam como `ENDPOINTS` que podem ser integrados e utilizados por outros serviços ou aplicações, bastando somente possuir o `Token de acesso da API`.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ActionsProcessDocsResponse', 'model/ActionsProcessProtocolResponse', 'model/ActionsProcessosCopyResponse', 'model/ActionsStatusResponse', 'model/Documento', 'model/IntimacoesResponse', 'api/AcoesApi', 'api/CopiasApi', 'api/EscutasApi', 'api/IntimacoesApi', 'api/ProtocolosApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ActionsProcessDocsResponse'), require('./model/ActionsProcessProtocolResponse'), require('./model/ActionsProcessosCopyResponse'), require('./model/ActionsStatusResponse'), require('./model/Documento'), require('./model/IntimacoesResponse'), require('./api/AcoesApi'), require('./api/CopiasApi'), require('./api/EscutasApi'), require('./api/IntimacoesApi'), require('./api/ProtocolosApi'));
  }
}(function(ApiClient, ActionsProcessDocsResponse, ActionsProcessProtocolResponse, ActionsProcessosCopyResponse, ActionsStatusResponse, Documento, IntimacoesResponse, AcoesApi, CopiasApi, EscutasApi, IntimacoesApi, ProtocolosApi) {
  'use strict';

  /**
   * Bem_vindo_a_documentao_da_API_do__Intima_ai_httpsapp_intima_ai__Est_documentao_cobre_todas_as_aes_disponveis_dentro_do_Intima_ai_e_as_disponibilizam_como_ENDPOINTS_que_podem_ser_integrados_e_utilizados_por_outros_servios_ou_aplicaes_bastando_somente_possuir_o_Token_de_acesso_da_API_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var IntimaaiApi = require('index'); // See note below*.
   * var xxxSvc = new IntimaaiApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new IntimaaiApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new IntimaaiApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new IntimaaiApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ActionsProcessDocsResponse model constructor.
     * @property {module:model/ActionsProcessDocsResponse}
     */
    ActionsProcessDocsResponse: ActionsProcessDocsResponse,
    /**
     * The ActionsProcessProtocolResponse model constructor.
     * @property {module:model/ActionsProcessProtocolResponse}
     */
    ActionsProcessProtocolResponse: ActionsProcessProtocolResponse,
    /**
     * The ActionsProcessosCopyResponse model constructor.
     * @property {module:model/ActionsProcessosCopyResponse}
     */
    ActionsProcessosCopyResponse: ActionsProcessosCopyResponse,
    /**
     * The ActionsStatusResponse model constructor.
     * @property {module:model/ActionsStatusResponse}
     */
    ActionsStatusResponse: ActionsStatusResponse,
    /**
     * The Documento model constructor.
     * @property {module:model/Documento}
     */
    Documento: Documento,
    /**
     * The IntimacoesResponse model constructor.
     * @property {module:model/IntimacoesResponse}
     */
    IntimacoesResponse: IntimacoesResponse,
    /**
     * The AcoesApi service constructor.
     * @property {module:api/AcoesApi}
     */
    AcoesApi: AcoesApi,
    /**
     * The CopiasApi service constructor.
     * @property {module:api/CopiasApi}
     */
    CopiasApi: CopiasApi,
    /**
     * The EscutasApi service constructor.
     * @property {module:api/EscutasApi}
     */
    EscutasApi: EscutasApi,
    /**
     * The IntimacoesApi service constructor.
     * @property {module:api/IntimacoesApi}
     */
    IntimacoesApi: IntimacoesApi,
    /**
     * The ProtocolosApi service constructor.
     * @property {module:api/ProtocolosApi}
     */
    ProtocolosApi: ProtocolosApi
  };

  return exports;
}));
